name: Github Page Deploy Workflow

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env
        run: |
          touch .env
          echo CI = false >> .env
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm i --force
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
